name: hello_world

on:
  push:
    branches:
      - child_branch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello World
        run: echo "Hello, World"

